name: testing-demo

services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:latest
        environment:
        - "SA_PASSWORD=Test123!"
        - "ACCEPT_EULA=Y"
        - "MSSQL_AGENT_ENABLED=true"
        - "MSSQL_PID=Express"
        ports:
        - 1434:1433

    elasticsearch:
        image: elasticsearch:8.15.1
        environment:
        - "discovery.type=single-node"
        ports:
        - 9200:9200
        - 9300:9300

    kibana:
        image: kibana:8.15.1
        environment:
        - "xpack.security.enabled=false"
        ports:
        - 5601:5601

    rabbitmq:
        image: rabbitmq:3.13-management
        ports:
        - 5672:5672
        - 15672:15672